apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FrejaMeyer/MyBookStore.git
    targetRevision: HEAD
    path: k8s                      # path to folder containing your YAMLs
  destination:
    server: https://kubernetes.default.svc/
    namespace: default             # where you want everything deployed
  syncPolicy:
    automated:                     # optional: enable auto-sync
      prune: true
      selfHeal: true