apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
        - name: workflow
          image: workflow-service:dev
          ports:
            - containerPort: 8080