apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket
  template:
    metadata:
      labels:
        app: basket
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "basketservice"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: basket
          image: frejameyer/basket@sha256:e3d2c8b6c531ed161e9b7e8444b408f3ed9e2410cf4f33d5ed8ed04f775cc173
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"


