apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket
  template:
    metadata:
      labels:
        app: basket
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "basketservice"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: basket
          image: frejameyer/basket@sha256:f332f80c90d3c02d06095def2d73c269097934fb6c385e102d57d4fbfb844d52
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"


