apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: frejameyer/catalog@sha256:1b80574419e2f019252c56265f3ab5e1fbe7a6a7ff56cde8dcb7cb5d1a3645aa
          ports:
            - containerPort: 8080