apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderservice"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: inventory
          image: frejameyer/inventory@sha256:43ba4bb0f5d8adaa91b0bb71531f319c7bc9b764dac2277a8c3d5d076e8f9a0e
          ports:
            - containerPort: 8080
  
