apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "paymentservice"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: payment 
          image: frejameyer/payment@sha256:c41d9159d8a8c95531f73be60e3849312b9d5bc0836e3fd989252cfae7a1b563
          ports:
            - containerPort: 8080
