apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bookpubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis-master-master.default.svc.cluster.local:6379
    - name: redisPassword
      value: ""
