apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
        - name: workflow
          image: frejameyer/workflow@sha256:1b4eff68b57a8de5a6b5129d27dfa943edf892e3c0e2c54b4ed1e4499b8b16ac
          ports:
            - containerPort: 8080